### ISSUE TITLE
No support for custom image models.

### ISSUE THREAD

**Issue by KalobTaulien** [KalobTaulien/wagtail-tinypng#4]
Needs to support wagtail custom image models.

**Comment by KalobTaulien** [comment]
Fixed.

**Comment by christophz** [comment]
> Fixed.

Is it? Because when I want to sync the images or upload a new one I get

`ValueError: Cannot query "########.jpg": Must be "Image" instance.`

I have a custom image model:

```
class CustomImage(AbstractImage):
    copyright = models.CharField(blank=True, max_length=120)

    admin_form_fields = Image.admin_form_fields + ("copyright",)
```
