### ISSUE TITLE
Management command sync_tinypng_images is missing

### ISSUE THREAD

**Issue by sanderdatema** [KalobTaulien/wagtail-tinypng#6]
While it is mentioned in the docs and in #5, it seems `sync_tinypng_images` was never implemented. Anyway, I can't find it anywhere in the code.

**Comment by KalobTaulien** [comment]
Hey @sanderdatema ,

I'm glad you reported this! I forgot to add it to the pypi package. `pip install wagtailtinypng --upgrade` will upgrade you to `v0.0.3` and you'll have access to the management command now.
